version: "2"
services:
  mongo:
    image: mongo:3.2.4
    restart: always
  crater:
    image: jedwards1211/crater:$TAG
    ports:
      - "3000:80"
    environment:
      - ROOT_URL=$ROOT_URL
    depends_on:
      - mongo
